MT#55283 add -latomic
This is needed on armel due to

/usr/bin/ld: ./../lib/auxlib.h:513: undefined reference to `__atomic_compare_exchange_8'
/usr/bin/ld: ./../lib/auxlib.h:507: undefined reference to `__atomic_load_8'

etc

Change-Id: I37793cb4d166a9cd8004a7a6b45ce67cb98d3798
(cherry picked from commit 5406e4efd8581ddf7045342ba3477548d77ae369)