Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> > Patch Set 5:
> > 
> > The travis builds are failing for me btw:
> > 
> >   https://travis-ci.com/github/mika/rtpengine/jobs/338423067
> > 
> > Richard, do you actually use the travis builds? Otherwise I'd suggest to drop it and suggest fully switching to Github actions instead.
> > 
> > The build against Debian/unstable failed for me:
> > 
> >   https://github.com/mika/rtpengine/runs/708540938?check_suite_focus=true
> > 
> > with:
> > 
> > ssllib.c:92:13: error: redefinition of 'make_OpenSSL_thread_safe'
> >    92 | static void make_OpenSSL_thread_safe(void) {
> >       |             ^~~~~~~~~~~~~~~~~~~~~~~~
> > ssllib.c:40:13: note: previous definition of 'make_OpenSSL_thread_safe' was here
> > 
> > FYI
> 
> I'm not using the Travis builds, but if there's a failure, it should be addresses.

See https://travis-ci.com/github/mika/rtpengine/jobs/338423067 ->

| Dependency is not satisfiable: debhelper-compat (= 12)

So this is broken since at least 2019-07-03 / commit 2868fc6f5

> AFAIK this error is unrelated to the changes and happens
> if there's a race condition during concurrent builds,
> e.g. multiple make instances trying to build the same file
> at the same time. Is that something specific to the Travis build environment?

It's failing in the Github environment (see https://github.com/mika/rtpengine/runs/708540938), but I can't reproduce it locally inside docker/unstable env. Hmmmm...

Patch-set: 5
Reviewer: Gerrit User 1000000 <1000000@85315e57-5f03-49c3-83f8-201ae2313a75>