Add missing errno.h
Fixes the following compilation error:

dtmf.c: In function 'dtmf_init':
dtmf.c:15:77: error: 'errno' undeclared (first use in this function)
    ilog(LOG_ERR, "Failed to open/connect DTMF logging socket: %s", strerror(errno));