MT#56471 fix tests on 32-bit
Fixes "undefined reference to `__atomic64_mutex'"

Fixes #1639

Change-Id: I3193bbe43b40419ec21cbb100843ae69ff1595f2
(cherry picked from commit 31d8adbe65d2ae356b13a58ff805fc2f9c053be7)