MT#55283 Fix deb build
/usr/include/mosquitto/libcommon_cjson.h:31:10: fatal error: cjson/cJSON.h: No such file or directory
   31 | #include <cjson/cJSON.h>
      |          ^~~~~~~~~~~~~~~

Temporary until Sid packaging is fixed.

Closes #2101

Change-Id: I485835400634c0d4a32732118aa936eeb8cb9f0f
Ref: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1135697
(cherry picked from commit 868cafbbc120c37add499dea36e030e5ed5fea77)
(cherry picked from commit 6cc616ba94b27c3e333c0fbab64f8bc5cc4846c4)